# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerup',
            name='icon_url',
            field=models.CharField(default='question_images/feil_synapse.jpg', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='terminal',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
