# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 21:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20161001_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerpowerup',
            name='quantity',
        ),
    ]
