# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_terminal_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerup',
            name='icon_url',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
