# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_badge_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
