# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_playerpowerup_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerpowerup',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
