# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 01:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_playerquestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerquestion',
            old_name='correct',
            new_name='is_correct',
        ),
    ]
