# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20161019_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerquestion',
            name='elapsed_time',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
