# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_badge_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='uid',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
