# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20161005_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
