# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_player_icon_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='active',
        ),
    ]
